spring:
  application:
    name: PetAnalogAvito
  liquibase:
    enabled: false
    change-log:
    url:
    user:
    password:
    database-change-log-table:
    database-change-log-lock-table:
    liquibase-schema:
    default-schema:

